version: '3.8'

services:
  redirector:
    image: nginx:stable-alpine
    container_name: redirector
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
